import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import Footer from '../components/Footer';
function Spinner() { return (<svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>); }
export default function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false); const { resetPassword } = useAuth();
  async function handleSubmit(e) { e.preventDefault(); setError(''); setLoading(true); try { await resetPassword(email); setSent(true); } catch (err) { setError(err.message || 'Failed.'); } finally { setLoading(false); } }
  if (sent) return (<div className="min-h-screen flex flex-col items-center justify-center px-6 bg-[#FAF5ED]"><div className="max-w-md w-full text-center p-8 bg-white border border-[#E8DFD4] rounded-2xl shadow-sm"><div className="text-6xl mb-6">📧</div><h1 className="text-2xl font-bold text-[#1a1a2e] mb-3" style={{ fontFamily: 'Poppins, sans-serif' }}>Check your email</h1><p className="text-[#6b7280] mb-6 text-sm">We sent a reset link to <strong className="text-[#1a1a2e]">{email}</strong>.</p><Link to="/login" className="inline-block px-6 py-3 text-white font-semibold rounded-xl transition-all duration-200 hover:scale-[1.02] text-sm" style={{ background: 'linear-gradient(135deg, #8B6914, #C4956A)' }}>Back to Sign In</Link></div><div className="mt-8"><Footer /></div></div>);
  return (<div className="min-h-screen flex flex-col items-center justify-center px-6 bg-[#FAF5ED]"><div className="max-w-md w-full"><div className="mb-6"><Link to="/login" className="text-[#5B8C7A] hover:text-[#4a7a6a] font-medium text-sm transition">&larr; Back to sign in</Link></div><div className="p-8 bg-white border border-[#E8DFD4] rounded-2xl shadow-sm"><h1 className="text-2xl font-bold text-[#1a1a2e] mb-2" style={{ fontFamily: 'Poppins, sans-serif' }}>Reset your password</h1><p className="text-[#9ca3af] mb-6 text-sm">Enter your email and we'll send you a reset link.</p>{error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-sm text-red-600">{error}</div>}<form onSubmit={handleSubmit} className="space-y-5"><div><label className="block text-sm font-medium text-[#4a5568] mb-1.5">Email</label><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="w-full px-4 py-3 bg-[#F5EFE6] border border-[#E8DFD4] rounded-xl text-[#1a1a2e] placeholder-[#9ca3af] focus:outline-none focus:ring-2 focus:ring-[#8B6914] focus:border-transparent transition-all duration-200 text-sm" placeholder="name@example.com" /></div><button type="submit" disabled={loading} className="w-full py-3.5 text-white font-semibold rounded-xl transition-all duration-200 hover:scale-[1.02] hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2" style={{ background: 'linear-gradient(135deg, #8B6914, #C4956A)', boxShadow: '0 4px 15px rgba(139,105,20,0.25)' }}>{loading ? (<><Spinner /> Sending...</>) : 'Send Reset Link'}</button></form></div></div><div className="mt-8"><Footer /></div></div>);
}
