import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import Footer from '../components/Footer';
function Spinner() { return (<svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>); }
export default function ResetPasswordPage() {
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const { updatePassword } = useAuth(); const navigate = useNavigate(); const [searchParams] = useSearchParams();
  useEffect(() => { if (!searchParams.get('code')) setError('Invalid or expired reset link.'); }, [searchParams]);
  async function handleSubmit(e) { e.preventDefault(); setError(''); if (password !== confirmPassword) { setError('Passwords do not match.'); return; } if (password.length < 6) { setError('Password must be at least 6 characters.'); return; } setLoading(true); try { await updatePassword(password); setSuccess(true); setTimeout(() => navigate('/dashboard'), 3000); } catch (err) { setError(err.message || 'Failed.'); } finally { setLoading(false); } }
  if (success) return (<div className="min-h-screen flex flex-col items-center justify-center px-6 bg-[#FAF5ED]"><div className="max-w-md w-full text-center p-8 paper-card"><div className="text-6xl mb-6">✅</div><h1 className="text-2xl font-bold text-[#1a1a2e] mb-3" style={{ fontFamily: 'Poppins, sans-serif' }}>Password updated</h1><p className="text-[#6b7280] text-sm">Redirecting you to the dashboard...</p></div><div className="mt-8"><Footer /></div></div>);
  return (<div className="min-h-screen flex flex-col items-center justify-center px-6 bg-[#FAF5ED]"><div className="max-w-md w-full"><div className="p-8 paper-card"><h1 className="text-2xl font-bold text-[#1a1a2e] mb-2" style={{ fontFamily: 'Poppins, sans-serif' }}>Set new password</h1><p className="text-[#9ca3af] mb-6 text-sm">Choose a strong new password.</p>{error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-sm text-red-600">{error}</div>}<form onSubmit={handleSubmit} className="space-y-5"><div><label className="block text-sm font-medium text-[#4a5568] mb-1.5">New Password</label><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required className="w-full px-4 py-3 paper-input text-[#1a1a2e] placeholder-[#9ca3af] text-sm" placeholder="••••••••" /></div><div><label className="block text-sm font-medium text-[#4a5568] mb-1.5">Confirm Password</label><input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} required className="w-full px-4 py-3 paper-input text-[#1a1a2e] placeholder-[#9ca3af] text-sm" placeholder="••••••••" /></div><button type="submit" disabled={loading} className="w-full py-3.5 text-white font-semibold rounded-xl transition-all duration-200 hover:scale-[1.02] hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2" style={{ background: 'linear-gradient(135deg, #8B6914, #C4956A)', boxShadow: '0 4px 15px rgba(139,105,20,0.25)' }}>{loading ? (<><Spinner /> Updating...</>) : 'Update Password'}</button></form></div></div><div className="mt-8"><Footer /></div></div>);
}
